---
title: Matti Besser — Product Design and Frontend Code
timezone: UTC+1
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  case_studies:
    output: true
    permalink: /:collection/:name
email: hello@mattibesser.com
description: 'Freelance web designer and front-end developer based in Berlin. Focussing
  on HTML and CSS.

'
baseurl: ''
url: http://mattibesser.com
author: Matti Besser
twitter_username: m_besser
github_username: mbesser
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
sass:
  sass_dir: assets/sass
  style: :compressed
include:
  - _case_studies
exclude:
- Gemfile
- Gemfile.lock
- package.json
- README.md
- CNAME
- node_modules
gems:
- jekyll-feed
- jekyll-sitemap
