# Site settings
title: Matti Besser — Webdesign and Frontend Development
email: hello@mattibesser.com
description: Freelance web designer and front-end developer based in Berlin. Focusing on HTML and CSS I code what I design.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mattibesser.com" # the base hostname & protocol for your site
twitter_username: m_besser
github_username:  mbesser
highlighter: pygments

# Build settings
markdown: kramdown
input: GFM
permalink: none

# Server settings
port: 1337
